To Do list: add & remove & interactive list
rica213/to-do-list pull request #2
Opened 2023-01-26 22:51 UTC by rica213

✅ Remove all hardcoded items from the tasks array.
✅ Create a new JavaScript file for the new functionality.
✅ Implement a function for adding a new task (add a new element to the array).
✅ Implement a function for deleting a task (remove an element from the array).
✅ Implement a function for editing task descriptions.
✅ By default, new tasks have the property completed set to false and the property index set to the value of the new array length.
✅ Deleting a task should update all remaining items' indexes, so they represent the current list order and are unique.
✅ All changes to the To Do List should be saved in local storage.
✅ Add event listener to the checkbox (change).
✅ Update items object's value for completed key upon user actions.
✅ Implement a function for the "Clear all completed" button (use filter() method).
✅ Store the updated array of items in local storage, so the user gets the correct list of values after the page reloads.

2023-01-26 23:49 UTC, Felix45 requested changes
Hi @rica213 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif" />

## Highlights :heavy_check_mark: 
- [ ] Application works as expected :white_check_mark: 
- [ ] GitHub flow is used correctly :white_check_mark: 
- [ ] Descriptive pull request title and summary :white_check_mark: 
- [ ]  Good descriptive commit messages :white_check_mark: 


## Required Changes ♻️

- [ Required ] I think it would be better if you included a `LICENSE` in your project directory to show anyone who would like to use your code how the project is licensed. You can use the [ MIT LICENSE](https://choosealicense.com/licenses/mit/)  provided on this link. Remember to customize the contents of the file e.g `Name`

![Screenshot from 2023-01-27 02-33-11](https://user-images.githubusercontent.com/16392046/214975270-304772be-7aa6-4a8d-a905-e019c243a4cc.png)

- [ Required ] It would be better if all the links on your `readme` file are active links, currently, your live demo link leads to a `404` page not found. I suggest you change it to the text `Not available` and only include the link once you deploy your project online.


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-26 23:49 UTC, Felix45 commented on src/index.js
>  /* eslint-disable no-underscore-dangle */
- [ Required ] I think It would be best if you don't disable `eslint` linter commands, this is because the default linter configuration helps you as a developer to write clean code. While you might have used the `underscore` to indicate private fields in your classes, I suggest that you don't use it if it means disabling linter checks. 

Use `this.tasks` instead of `this._tasks`
Use `this.completed` instead of `this._completed`
Use `this.description` instead of `this._description`
Use `this.index` instead of `this._index`

2023-01-26 23:49 UTC, Felix45 commented on src/modules/add.js
> +/* eslint-disable consistent-return */
- [ Required ] I think It would be best if you don't disable `eslint` linter commands, this is because the default linter configuration helps you as a developer to write clean code. While you might have used the `underscore` to indicate private fields in your classes, I suggest that you don't use it if it means disabling linter checks. 

Use `this.tasks` instead of `this._tasks`
Use `this.completed` instead of `this._completed`
Use `this.description` instead of `this._description`
Use `this.index` instead of `this._index`

2023-01-26 23:49 UTC, Felix45 commented on src/modules/add.js
> +    event.preventDefault();
- [ Required ] I think it would be better if you returned `false` after the `event.preventDefault()` this will make it unnecessary to disable the `consistent-return` rule in `eslint` and help keep your code base clean
```JavaScript
  const add = (event) => {
  if (newTask.value === '') {
    event.preventDefault();
    return false;
  } else {
    const task = new Task(newTask.value, false, currentTasks.tasks.length + 1);
    newTask.value = '';
    return task;
  }
};
```

2023-01-27 11:52 UTC, frank1738 approved these changes
Hi @rica213 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/J8FZIm9VoBU6Q/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-27 12:13 UTC, merged